### ISSUE TITLE
플레이어 서버 접속시

### ISSUE THREAD

**Issue by cccgh5** [HQService/HQFramework#22]
java.lang.NoSuchMethodError: 'void kr.hqservice.framework.database.repository.player.packet.handler.PlayerConnectionPacketHandler$onLoad$2.<init>(kr.hqservice.framework.database.repository.player.packet.handler.PlayerConnectionPacketHandler$handlerProxy, kr.hqservice.framework.nms.event.PlayerDataPreLoadEvent, kotlin.coroutines.Continuation)'
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.database.repository.player.packet.handler.PlayerConnectionPacketHandler$handlerProxy.onLoad(PlayerConnectionPacketHandler.kt:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.bukkit.core.listener.SuspendEventExecutor$execute$1.invokeSuspend(SuspendEventExecutor.kt:39)
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.bukkit.core.listener.SuspendEventExecutor$execute$1.invoke(SuspendEventExecutor.kt)
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.bukkit.core.listener.SuspendEventExecutor$execute$1.invoke(SuspendEventExecutor.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.bukkit.core.listener.SuspendEventExecutor.execute(SuspendEventExecutor.kt:34)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at hqframework-bukkit-dist.jar//kr.hqservice.framework.nms.handler.PacketHandler.write(PacketHandler.kt:23)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
	at eco-6.65.4-all.jar//com.willfp.eco.internal.spigot.proxy.v1_19_R3.common.packet.EcoChannelDuplexHandler.write(EcoChannelDuplexHandler.kt:42)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by vjh0107** [comment]
Publish 문제로 보입니다 수정하겠습니다
